services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"   # API
      - "9001:9001"   # Web UI
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    command: server /data --console-address ":9001"

volumes:
  minio_data:
